### ISSUE TITLE
Exception calling "ToInt32" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by rick-jordan** [MicroFocus/ADM-TFS-Extension#25]
Hi all,

I am getting the following error when starting the Run FileSystem task:
Exception calling "ToInt32" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.

![image](https://user-images.githubusercontent.com/62395332/130955260-6d48f9af-4c01-41b9-9dd3-72f43d1f76aa.png)

I am struggling on this point and I don't know how to solve it ... can someone help me? The last version that I was using (1.1.0) was working fine.

Regards

Diogo

**Comment by PaulaPaltinisanu** [comment]
Hello Diogo,

Thank you for reaching out!
Are the pipelines you are using of **release** or **build** type?

Could you maybe try to edit your localTask.ps1 to have the script's lines to be like the ones below and rerun your pipeline?$buildNumber = $env:RELEASE_RELEASEID
$attemptNumber = $env:RELEASE_ATTEMPTNUMBER

Please let us know if making this change has solved your issue.
Thank you!

**Comment by PaulaPaltinisanu** [comment]
Hello,

Due to the lack of activity, this issue will closed.
If you happen to encounter any problems, please raise a new issue.

Thank you!
