### ISSUE TITLE
Error "Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument"." after running Azure Pipeline task RunFromFileSystemTask

### ISSUE THREAD

**Issue by riknows** [MicroFocus/ADM-TFS-Extension#50]
Hi. Im getting this error after running the RunFromFileSystemTask in Azure.
![image](https://user-images.githubusercontent.com/98139958/150462372-d2c4a31b-2c1e-4d77-8d11-0cbd7bb78385.png)

MicroFocus UFT version: 14.53

XML result file produced from run.

<?xml version="1.0"?>
<testsuites xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <testsuite tests="1" failures="0" errors="0" time="653.872" package="FTToolsLauncher">
    <testcase name="C:\uft-automation-suite\Subject\S_SUP_PB_DB_Full_Rollover" report="C:\uft-automation-suite\Subject\S_SUP_PB_DB_Full_Rollover\Report3" time="653.806042" classname="All-Tests.Test group" status="pass">
      <system-out>21/01/2022 13:24:12 Running test: C:\uft-automation-suite\Subject\S_SUP_PB_DB_Full_Rollover ...
21/01/2022 13:24:12 Report path is automatically generated: C:\uft-automation-suite\Subject\S_SUP_PB_DB_Full_Rollover\Report3
21/01/2022 13:24:12 Launching testing tool ...
Running test: C:\uft-automation-suite\Subject\S_SUP_PB_DB_Full_Rollover
Test result: Passed
21/01/2022 13:35:06 Test completed in 654 seconds: C:\uft-automation-suite\Subject\S_SUP_PB_DB_Full_Rollover
21/01/2022 13:35:06 Test report is generated at: C:\uft-automation-suite\Subject\S_SUP_PB_DB_Full_Rollover\Report3
-------------------------------------------------------------------------------------------------------
</system-out>
    </testcase>
  </testsuite>
</testsuites>

**Comment by riknows** [comment]
To add, I worked out why it was failing. If I run the RunFromFileSystem Task and used a .mtb file to specify the test. the task fails with the above error message. But when I run the RunFromFileSystem task specifying the test file path, the task works.

**Comment by PaulaPaltinisanu** [comment]
Hi,
Thank you for reaching out to us!

Could you please provide more details, for us to narrow down the issue's cause?
The most relevant are:

- What is your current extension version? Have you performed an upgrade recently? If the case, has this issue reproduced with a previous version?
- _File System_ task's configuration - you can provide us with the generated props.txt file.
- Do any issues occur when using the other tasks the extension provides?


Thank you!

**Comment by PaulaPaltinisanu** [comment]
> To add, I worked out why it was failing. If I run the RunFromFileSystem Task and used a .mtb file to specify the test. the task fails with the above error message. But when I run the RunFromFileSystem task specifying the test file path, the task works.

Hello,
The .mtbx format is supported for specifying the tests. Could you please share the file with us, to better understand the root cause?

Thank you!

**Comment by PaulaPaltinisanu** [comment]
Hello,

Due to the lack of activity, this issue will closed.
If you happen to encounter any problems, please raise a new issue.

Thank you!
